### ISSUE TITLE
Não seria melhor desabilitar uma função desnecessária? [configuração de linha de comando]

### ISSUE THREAD

**Issue by frenetic** [phppe/FacilMVC#1]
De acordo com a documentação do PHP, ao executar a engine em linha de comando as funções de autoload não funcionam.
http://br.php.net/manual/en/language.oop5.autoload.php

Não seria melhor desabilitar (comentar até outro momento) as funções específicas de CLI?

No caso, apenas comentar a linha 84 do arquivo controlador/Facil.php removeria uma execução de algo que está em desuso.
https://github.com/phppe/FacilMVC/blob/master/controlador/Facil.php#L84

**Comment by berardo** [comment]
Oi Guilherme,
Na verdade acredito que a documentação se refira a não suportar autoload em scripts CLI em modo interativo, que entendo como código PHP sendo escrito diretamente pelo usuário (um heredoc da vida).
Já utilizo o Facil em projetos onde preciso registrar alguma ação dele em crontab e esse método tem salvo minha vida ;)

**Comment by frenetic** [comment]
Assim sendo, beleza :D

Dúvida respondida.
